import ri from "./runeImages";

export default {
  Precision: [
    [
      ri.Precision.PressTheAttack,
      ri.Precision.LethalTempo,
      ri.Precision.FleetFootwork,
      ri.Precision.Conqueror,
    ],
    [
      ri.Precision.Overheal, 
      ri.Precision.Triumph, 
      ri.Precision.PresenceOfMind
    ],
    [
      ri.Precision.LegendAlacrity,
      ri.Precision.LegendTenacity,
      ri.Precision.LegendBloodline,
    ],
    [
      ri.Precision.CoupDeGrace, 
      ri.Precision.CutDown, 
      ri.Precision.LastStand
    ],
  ],
  Domination: [
    [
      ri.Domination.Electrocute,
      ri.Domination.Predator,
      ri.Domination.DarkHarvest,
      ri.Domination.HailOfBlades,
    ],
    [
      ri.Domination.CheapShot,
      ri.Domination.TasteOfBlood,
      ri.Domination.SuddenImpact,
    ],
    [
      ri.Domination.ZombieWard,
      ri.Domination.GhostPoro,
      ri.Domination.EyeballCollection,
    ],
    [
      ri.Domination.RavenousHunter,
      ri.Domination.IngeniousHunter,
      ri.Domination.RelentlessHunter,
      ri.Domination.UltimateHunter,
    ],
  ],
  Sorcery: [
    [
      ri.Sorcery.SummonAery,
      ri.Sorcery.ArcaneComet,
      ri.Sorcery.PhaseRush,
    ],
    [
      ri.Sorcery.NullifyingOrb,
      ri.Sorcery.ManaflowBand,
      ri.Sorcery.NimbusCloak,
    ],
    [
      ri.Sorcery.Transcendence,
      ri.Sorcery.Celerity,
      ri.Sorcery.AbsoluteFocus,
    ],
    [
      ri.Sorcery.Scorch,
      ri.Sorcery.Waterwalking,
      ri.Sorcery.GatheringStorm,
    ],
  ],
  Resolve: [
    [
      ri.Resolve.GraspOfTheUndying,
      ri.Resolve.Aftershock,
      ri.Resolve.Guardian,
    ],
    [
      ri.Resolve.Demolish,
      ri.Resolve.FontOfLife,
      ri.Resolve.ShieldBash,
    ],
    [
      ri.Resolve.Conditioning,
      ri.Resolve.SecondWind,
      ri.Resolve.BonePlating,
    ],
    [
      ri.Resolve.Overgrowth,
      ri.Resolve.Revitalize,
      ri.Resolve.Unflinching,
    ],
  ],
  Inspiration: [
    [
      ri.Inspiration.GlacialAugment,
      ri.Inspiration.UnsealedSpellbook,
      ri.Inspiration.PrototypeOmnistone,
    ],
    [
      ri.Inspiration.HextechFlashtraption,
      ri.Inspiration.MagicalFootwear,
      ri.Inspiration.PerfectTiming,
    ],
    [
      ri.Inspiration.FuturesMarket,
      ri.Inspiration.MinionDematerializer,
      ri.Inspiration.BiscuitDelivery,
    ],
    [
      ri.Inspiration.CosmicInsight,
      ri.Inspiration.ApproachVelocity,
      ri.Inspiration.TimeWarpTonic,
    ]
  ],
  StatMods: [
    [
      ri.StatMods.AdaptiveForceIcon,
      ri.StatMods.AttackSpeedIcon,
      ri.StatMods.CDRScalingIcon,
    ],
    [
      ri.StatMods.AdaptiveForceIcon,
      ri.StatMods.ArmorIcon,
      ri.StatMods.MagicResIcon,
    ],
    [
      ri.StatMods.HealthScalingIcon,
      ri.StatMods.ArmorIcon,
      ri.StatMods.MagicResIcon,
    ]
  ]
};
