var context = require.context("./assets/Chars", false, /\.jpg$/);

export default {
  Акали: context("./Акали.jpg"),
  Мордекайзер: context("./Мордекайзер.jpg"),
  Сетт: context("./Сетт.jpg"),
  Юми: context("./Юми.jpg"),
  Волибир: context("./Волибир.jpg"),
  Ёнэ: context("./Ёнэ.jpg"),
  Зерат: context("./Зерат.jpg"),
  Ари: context("./Ари.jpg"),
  Люкс: context("./Люкс.jpg"),
  Эш: context("./Эш.jpg"),
  Моргана: context("./Моргана.jpg"),
  "Мастер Йи": context("./Мастер Йи.jpg"),
  "Мисс Фортуна": context("./Мисс Фортуна.jpg"),
  Сорака: context("./Сорака.jpg"),
  Сона: context("./Сона.jpg"),
  Талон: context("./Талон.jpg"),
  Зайра: context("./Зайра.jpg"),
  Эзреаль: context("./Эзреаль.jpg"),
  Леона: context("./Леона.jpg"),
  Каин: context("./Каин.jpg"),
  Пайк: context("./Пайк.jpg"),
  Ясуо: context("./Ясуо.jpg"),
  Скарнер: context("./Скарнер.jpg"),
  Эвелинн: context("./Эвелинн.jpg"),
  Киндред: context("./Киндред.jpg"),
  Гарен: context("./Гарен.jpg"),
  Пантеон: context("./Пантеон.jpg"),
  Фиддлстикс: context('./Фиддлстикс.jpg')
};
